title: 3gstudent-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "3gstudent"
  email: "no"
  url: "https://3gstudent.github.io/"

baseurl: /3gstudent.github.io/

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "3gstudent"
year : "2021"
